import Toybox.Test;

/*
 * The expected values in AstrometryRegressionReference.mc are generated by
 * tools/astrometry_regression.py with ERFA/pyerfa.  ERFA is a separately
 * compiled implementation of the SOFA algorithms, so this suite exercises
 * the complete Garmin begin -> step -> reticleAt path against an oracle that
 * does not share the production Monkey C implementation.
 */
function regressionAbsoluteError(actual, expected) {
    var error = actual - expected;
    return error < 0.0 ? -error : error;
}

function regressionAngleError(actual, expected) {
    var error = Astrometry.anp(actual - expected);
    if (error > Astrometry.D2PI / 2.0) {
        error = Astrometry.D2PI - error;
    }
    return error;
}

function regressionRunCase(fixture, logger) {
    var inputs = fixture[:inputs];
    var state = Astrometry.begin(
        inputs[0],
        inputs[1],
        inputs[2],
        inputs[3],
        inputs[4],
        inputs[5],
        inputs[6],
        inputs[7],
        inputs[8],
        inputs[9],
        inputs[10],
        inputs[11],
        inputs[12],
        inputs[13],
        inputs[14],
        inputs[15],
        inputs[16],
        inputs[17]
    );
    var reply = null;
    var done = false;
    var steps = 0;
    while (!done && steps < 500) {
        reply = Astrometry.step(state);
        state = reply[:state];
        done = reply[:done];
        steps += 1;
    }
    if (!done || reply == null || reply[:result] == null || reply[:result][:status] != 0) {
        logger.debug("independent oracle did not complete: " + fixture[:name]);
        return false;
    }
    
    var result = reply[:result];
    var expected = fixture[:anchor];
    var ok = true;
    var angular = AstrometryRegressionReference.ANGULAR_TOLERANCE;
    var hourAngle = AstrometryRegressionReference.HOUR_ANGLE_TOLERANCE;
    var tangent = AstrometryRegressionReference.TANGENT_TOLERANCE;
    // ERFA's atco13 outputs: azimuth, zenith distance, hour angle,
    // declination, right ascension, equation of origins.  The remaining four
    // values are the reticle tangent-plane projection used by the app.
    ok = ok && regressionAngleError(result[:aob], expected[0]) <= angular;
    ok = ok && regressionAbsoluteError(result[:zob], expected[1]) <= angular;
    ok = ok && regressionAngleError(result[:hob], expected[2]) <= hourAngle;
    ok = ok && regressionAbsoluteError(result[:dob], expected[3]) <= angular;
    ok = ok && regressionAngleError(result[:rob], expected[4]) <= angular;
    ok = ok && regressionAngleError(result[:eo], expected[5]) <= angular;
    ok = ok && regressionAbsoluteError(result[:reticleX], expected[6]) <= tangent;
    ok = ok && regressionAbsoluteError(result[:reticleY], expected[7]) <= tangent;
    ok = ok && regressionAngleError(result[:reticleHourAngle], expected[8]) <= hourAngle;
    ok = ok && regressionAbsoluteError(result[:reticlePoleDistance], expected[9]) <= angular;
    if (!ok) {
        logger.debug(
            "independent oracle anchor mismatch: " + fixture[:name] + " aob="
                + regressionAngleError(result[:aob], expected[0])
                + " zob="
                + regressionAbsoluteError(result[:zob], expected[1])
                + " hob="
                + regressionAngleError(result[:hob], expected[2])
                + " dob="
                + regressionAbsoluteError(result[:dob], expected[3])
                + " rob="
                + regressionAngleError(result[:rob], expected[4])
                + " eo="
                + regressionAngleError(result[:eo], expected[5])
                + " x="
                + regressionAbsoluteError(result[:reticleX], expected[6])
                + " y="
                + regressionAbsoluteError(result[:reticleY], expected[7])
                + " ha="
                + regressionAngleError(result[:reticleHourAngle], expected[8])
                + " pd="
                + regressionAbsoluteError(result[:reticlePoleDistance], expected[9])
        );
        return false;
    }
    
    // Compare the cheap between-anchor path at several elapsed times with a
    // fresh ERFA calculation.  This catches stale Earth rotation, sign/wrap,
    // refraction, and tangent-plane projection errors that an anchor-only
    // vector cannot see.
    var anchor = result[:reticleAnchor];
    var expectedSteps = fixture[:steps];
    for (var i = 0; i < expectedSteps.size(); i += 1) {
        var expectedStep = expectedSteps[i];
        var actualStep = Astrometry.reticleAt(anchor, expectedStep[0]);
        var stepOk = regressionAngleError(actualStep[:aob], expectedStep[1]) <= angular
            && regressionAbsoluteError(actualStep[:zob], expectedStep[2]) <= angular
            && regressionAbsoluteError(actualStep[:x], expectedStep[3]) <= tangent
            && regressionAbsoluteError(actualStep[:y], expectedStep[4]) <= tangent
            && regressionAngleError(actualStep[:hourAngle], expectedStep[5]) <= hourAngle
            && regressionAbsoluteError(actualStep[:poleDistance], expectedStep[6]) <= angular;
        if (!stepOk) {
            logger.debug(
                "independent oracle propagation mismatch: " + fixture[:name] + " t="
                    + expectedStep[0]
            );
            return false;
        }
    }
    return true;
}

(:test)
function independentAstrometryRegressionGrid(logger as Test.Logger) {
    var fixtures = AstrometryRegressionReference.CASES;
    for (var i = 0; i < fixtures.size(); i += 1) {
        if (!regressionRunCase(fixtures[i], logger)) {
            return false;
        }
    }
    return true;
}
