# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate checked-in IERS EOP data; only update accesses the network."""

import argparse
from collections import deque
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "iers"
OUTPUT = ROOT / "source" / "IersEopData.mc"
URL = "https://datacenter.iers.org/data/9/finals2000A.all"
DAYS = 368
MAX_START_AGE_DAYS = 7
MIN_FUTURE_DAYS = 330
EPOCH = date(1858, 11, 17)
NAME = re.compile(r"finals2000A-(\d{4}-\d{2}-\d{2})\.txt")
NUMBER = re.compile(r"[+-]?\d+\.\d+")


@dataclass(frozen=True)
class Row:
    mjd: int
    xp: str
    yp: str
    dut1: str


def number(text: str, field: str) -> Decimal:
    token = text.strip()
    if not NUMBER.fullmatch(token):
        raise ValueError(f"Missing or invalid {field}: {token!r}")
    return Decimal(token)


def parse_row(line: str) -> Row:
    if len(line) < 78 or line[16] not in "IP" or line[57] not in "IP":
        raise ValueError("Missing Bulletin A polar-motion or UT1 fields/flags")
    mjd = number(line[7:15], "MJD")
    if mjd != mjd.to_integral_value():
        raise ValueError(f"Nonintegral daily MJD: {mjd}")
    day = EPOCH + timedelta(days=int(mjd))
    calendar = tuple(int(line[a:b]) for a, b in ((0, 2), (2, 4), (4, 6)))
    if calendar != (day.year % 100, day.month, day.day):
        raise ValueError(f"Calendar date disagrees with MJD {mjd}")
    values = []
    for field, start, end in (("xp", 18, 27), ("yp", 37, 46), ("dut1", 58, 68)):
        value = number(line[start:end], field)
        # Seven places preserve the existing Monkey C literals without floats.
        token = format(value, ".7f")
        if Decimal(token) != value:
            raise ValueError(f"{field} exceeds supported seven-place precision")
        values.append(token)
    for field, start, end in (("xp error", 27, 36), ("yp error", 46, 55), ("dut1 error", 68, 78)):
        if number(line[start:end], field) < 0:
            raise ValueError(f"Negative {field}")
    return Row(int(mjd), *values)


def parse_snapshot(path: Path, content: bytes) -> list[Row]:
    match = NAME.fullmatch(path.name)
    if match is None:
        raise ValueError(f"Invalid snapshot filename: {path.name}")
    start = date.fromisoformat(match[1])
    lines = content.decode("ascii").splitlines()
    if len(lines) != DAYS:
        raise ValueError(f"Expected {DAYS} daily rows, got {len(lines)}")
    rows = []
    first = (start - EPOCH).days
    for index, line in enumerate(lines):
        try:
            row = parse_row(line)
            if row.mjd != first + index:
                raise ValueError(f"Expected MJD {first + index}, got {row.mjd}")
        except ValueError as error:
            raise ValueError(f"{path.name}:{index + 1}: {error}") from error
        rows.append(row)
    return rows


def snapshot() -> Path:
    paths = sorted(DATA.glob("finals2000A-*.txt"))
    if len(paths) != 1:
        raise ValueError(f"Expected exactly one dated IERS snapshot, found {len(paths)}")
    return paths[0]


def coverage(path: Path) -> tuple[date, date]:
    rows = parse_snapshot(path, path.read_bytes())
    return EPOCH + timedelta(days=rows[0].mjd), EPOCH + timedelta(days=rows[-1].mjd)


def check_freshness(path: Path, today: date) -> tuple[date, date]:
    start, end = coverage(path)
    age = (today - start).days
    remaining = (end - today).days
    if age < 0:
        raise ValueError(f"coverage starts in the future ({start}; today is {today})")
    if age > MAX_START_AGE_DAYS:
        raise ValueError(
            f"coverage starts {age} days ago ({start}); refresh is at most "
            f"{MAX_START_AGE_DAYS} days behind"
        )
    if remaining < MIN_FUTURE_DAYS:
        raise ValueError(
            f"coverage ends in {remaining} days ({end}); at least "
            f"{MIN_FUTURE_DAYS} future days are required"
        )
    return start, end


def render(path: Path, rows: list[Row]) -> bytes:
    first, last = rows[0].mjd, rows[-1].mjd
    if len(rows) != DAYS or any(row.mjd != first + i for i, row in enumerate(rows)):
        raise ValueError("Generated output requires 368 contiguous days")
    start, end = EPOCH + timedelta(days=first), EPOCH + timedelta(days=last)
    triplets = ",\n".join(f"        {row.xp},{row.yp},{row.dut1}" for row in rows)
    source = f"""/*
 * Generated by tools/iers.py; do not edit.
 * Source: {URL}
 * Snapshot: data/iers/{path.name}
 * IERS Bulletin A finals2000A; covering {start} through {end}.
 * xp/yp are arcsec; dut1 is seconds.
 */
import Toybox.Math;
module IersEopData {{
    // Contiguous daily triplets [xp, yp, dut1]; MJD is {first} + triplet index.
    var EOP = [
{triplets}
    ];
    function eop(mjd) {{
        mjd = mjd.toDouble();
        if (mjd < {first}.0 || mjd > {last}.0) {{ return {{:status => -1, :warning => false}}; }}
        var i = Math.floor(mjd - {first}.0).toNumber();
        if (i >= {DAYS - 1}) {{ i = {DAYS - 2}; }}
        var w = mjd - ({first}.0 + i);
        var a = i * 3;
        var b = a + 3;
        return {{:status => 0, :dut1 => EOP[a + 2] + w * (EOP[b + 2] - EOP[a + 2]), :xp => (EOP[a] + w * (EOP[b] - EOP[a])) * Astrometry.DAS2R, :yp => (EOP[a + 1] + w * (EOP[b + 1] - EOP[a + 1])) * Astrometry.DAS2R, :first => {first}.0, :last => {last}.0, :warning => ({last}.0 - mjd) <= 30.0}};
    }}
    function firstDate() {{ return {first}.0; }}
    function lastDate() {{ return {last}.0; }}
}}
""".encode("ascii")
    formatter = os.environ.get("MONKEYC_FMT", "monkeyc-fmt")
    return subprocess.run(
        [formatter],
        input=source,
        check=True,
        stdout=subprocess.PIPE,
    ).stdout


def stage(path: Path, content: bytes) -> Path:
    """Write beside the destination so replacement stays on the same filesystem."""
    descriptor, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    staged = Path(name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        staged.chmod(0o644)
    except BaseException:
        staged.unlink(missing_ok=True)
        raise
    return staged


def install(outputs: dict[Path, bytes], obsolete: Path | None = None) -> None:
    """Stage every output and rollback copy before touching installed files."""
    staged = {}
    backups = {}
    changed = []
    recovery = set()
    try:
        for path, content in outputs.items():
            staged[path] = stage(path, content)
            backups[path] = stage(path, path.read_bytes()) if path.exists() else None
        try:
            for path, temporary in staged.items():
                os.replace(temporary, path)
                changed.append(path)
            if obsolete is not None:
                obsolete.unlink()
        except BaseException as error:
            failures = []
            for path in reversed(changed):
                backup = backups[path]
                try:
                    if backup is None:
                        path.unlink(missing_ok=True)
                    else:
                        os.replace(backup, path)
                except OSError as rollback_error:
                    if backup is not None:
                        recovery.add(backup)
                    failures.append(f"{path}: {rollback_error}; backup: {backup}")
            if failures:
                raise OSError("Install failed and rollback needs recovery: " + "; ".join(failures)) from error
            raise
    finally:
        for temporary in (*staged.values(), *backups.values()):
            if temporary is not None and temporary not in recovery:
                temporary.unlink(missing_ok=True)


def select_snapshot(content: bytes, today: date) -> bytes:
    current = (today - EPOCH).days
    window: deque[tuple[Row, str]] = deque(maxlen=DAYS)
    selected: list[str] | None = None
    latest_start: int | None = None
    for line in content.decode("ascii").splitlines():
        try:
            row = parse_row(line)
        except (ValueError, OverflowError):
            # Official files extend past the last fully populated prediction.
            continue
        if window and row.mjd != window[-1][0].mjd + 1:
            window.clear()
        window.append((row, line))
        if len(window) != DAYS:
            continue
        first = window[0][0].mjd
        if (
            0 <= current - first <= MAX_START_AGE_DAYS
            and first <= current <= row.mjd
            and (latest_start is None or first > latest_start)
        ):
            selected = [source for _, source in window]
            latest_start = first
    if selected is None:
        raise ValueError(
            f"No contiguous {DAYS}-row complete coverage starts within seven days "
            f"before {today} and includes that date"
        )
    return ("\n".join(selected) + "\n").encode("ascii")


def update() -> None:
    old = snapshot()
    today = datetime.now(timezone.utc).date()
    # curl inherits the caller's proxy environment. Disable user curl config so
    # the fixed HTTPS source and failure behavior cannot be changed implicitly.
    downloaded = subprocess.run(
        ["curl", "--disable", "--fail", "--silent", "--show-error", "--location",
         "--proto", "=https", "--proto-redir", "=https", "--connect-timeout", "30",
         "--max-time", "120", URL],
        check=True, stdout=subprocess.PIPE,
    ).stdout
    content = select_snapshot(downloaded, today)
    first = parse_row(content.decode("ascii").splitlines()[0]).mjd
    start = EPOCH + timedelta(days=first)
    path = DATA / f"finals2000A-{start.isoformat()}.txt"
    rows = parse_snapshot(path, content)
    generated = render(path, rows)
    install({path: content, OUTPUT: generated}, old if old != path else None)
    end = EPOCH + timedelta(days=rows[-1].mjd)
    print(
        f"Updated {path.relative_to(ROOT)} and {OUTPUT.relative_to(ROOT)} "
        f"(coverage {start}–{end}, {DAYS} daily rows)"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "check", "check-freshness", "update"))
    command = parser.parse_args().command
    try:
        if command == "update":
            update()
            return 0
        path = snapshot()
        if command == "check-freshness":
            start, end = check_freshness(path, datetime.now(timezone.utc).date())
            print(f"IERS coverage is fresh: {start}–{end} ({MIN_FUTURE_DAYS}+ future days required)")
            return 0
        expected = render(path, parse_snapshot(path, path.read_bytes()))
        if command == "check":
            if not OUTPUT.exists() or OUTPUT.read_bytes() != expected:
                print("IERS generated data differs; run make generate-iers", file=sys.stderr)
                return 1
            print("IERS generated data is current")
        else:
            install({OUTPUT: expected})
            print(f"Generated {OUTPUT.relative_to(ROOT)}")
        return 0
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"iers: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
