import Toybox.Application;
import Toybox.Attention;
import Toybox.Graphics;
import Toybox.Lang;
import Toybox.Math;
import Toybox.Position;
import Toybox.Sensor;
import Toybox.System;
import Toybox.Time;
import Toybox.Time.Gregorian;
import Toybox.Timer;
import Toybox.WatchUi;

function focusVisibleScroll(rowTop, rowPitch, rowHalfHeight, drawableTop, drawableBottom, focus, scroll) {
  var center = rowTop + (focus - scroll) * rowPitch;
  while (center - rowHalfHeight < drawableTop) {
    scroll -= 1;
    center += rowPitch;
  }
  while (center + rowHalfHeight > drawableBottom) {
    scroll += 1;
    center -= rowPitch;
  }
  return scroll;
}

function atmosphereVisibleFocus(index, direction, manualPressure) {
  if (!manualPressure && index == 1) { return direction < 0 ? 0 : 2; }
  return index;
}

class PolarFinderView extends WatchUi.View {
  const LOCATE=0; const GPS=1; const EDIT_LAT=2; const EDIT_LON=3; const EDIT_ELEV=4; const ATMOS=5;
  const CALC=6; const DISPLAY=7; const ACTIONS=8; const DETAILS=9; const HELP=10; const GPS_WARNING=11;
  const DISCARD=12; const CALC_ERROR=13;
  const ROW_PITCH=42; const ROW_DRAWABLE_TOP=58; const ROW_DRAWABLE_BOTTOM=390;
  private var _model; private var _screen=LOCATE; private var _focus=0; private var _scroll=0; private var _rowTop=68; private var _rowHalfHeight=0; private var _editing=false;
  private var _timer; private var _gpsStarted=0; private var _gpsLat=null; private var _gpsLon=null; private var _gpsElev=null; private var _gpsQuality=""; private var _gpsQualityCode=0; private var _gpsReceived=0; private var _gpsWhen=null; private var _gpsError=null;
  private var _digits=[]; private var _negative=false; private var _editOriginal=null; private var _invalid=false;
  private var _calcStage=0; private var _progress=0; private var _pressureAttempts=0; private var _pressureSamples=[]; private var _cancelRequested=false; private var _restart=false; private var _errorText=null; private var _astroState=null;
  private var _result=null; private var _resultTime=null; private var _displayBase=0; private var _lastTick=0; private var _lastAnchor=0;
  private var _seaPressure=null; private var _observerPressure=0.0; private var _pressureSource=""; private var _pressureTime=null; private var _cachedSeaPressure=null; private var _cachedPressureTime=null; private var _eop=null; private var _ellipsoidHeight=null; private var _geoidOffset=null;
  private var _helpPage=0;

  function initialize(model){View.initialize();_model=model;_timer=new Timer.Timer();}
  function onLayout(dc){}
  function stopTimers(){if(_timer!=null){_timer.stop();}}
  function onHide(){stopTimers();}
  function onAppInactive(){stopTimers();if(_astroState!=null){Astrometry.cancel(_astroState);_astroState=null;}if(_screen==CALC){_restart=true;}else if(_screen==DISPLAY){_result=null;}}
  function onAppActive(){if(_screen==CALC&&_restart){beginCalculation(true);}else if(_screen==DISPLAY){beginCalculation(true);}}
  function s(id){return Application.loadResource(id);}
  function title(dc,text){dc.setColor(Graphics.COLOR_RED,Graphics.COLOR_TRANSPARENT);dc.drawText(227,8,Graphics.FONT_SMALL,text,Graphics.TEXT_JUSTIFY_CENTER);}
  function center(dc,y,font,text,color){dc.setColor(color,Graphics.COLOR_TRANSPARENT);dc.drawText(227,y,font,text,Graphics.TEXT_JUSTIFY_CENTER|Graphics.TEXT_JUSTIFY_VCENTER);}
  function centerFit(dc,y,text,color,preferred,fallback,maxWidth){var font=preferred;if(dc.getTextWidthInPixels(text,font)>maxWidth){font=fallback;if(dc.getTextWidthInPixels(text,font)>maxWidth){font=Graphics.FONT_XTINY;if(dc.getTextWidthInPixels(text,font)>maxWidth){return false;}}}center(dc,y,font,text,color);return true;}
  function footer(dc,text){center(dc,414,Graphics.FONT_XTINY,text,Graphics.COLOR_DK_GRAY);}
  function ensureFocusVisible(){if(_rowHalfHeight>0){_scroll=focusVisibleScroll(_rowTop,ROW_PITCH,_rowHalfHeight,ROW_DRAWABLE_TOP,ROW_DRAWABLE_BOTTOM,_focus,_scroll);}}
  function row(dc,index,label,value){
    var font=Graphics.FONT_XTINY;var fh=dc.getFontHeight(font);var rh=fh+8;
    if(index==0){_rowHalfHeight=rh/2;ensureFocusVisible();}
    var cy=_rowTop+(index-_scroll)*ROW_PITCH;if(cy-rh/2<ROW_DRAWABLE_TOP||cy+rh/2>ROW_DRAWABLE_BOTTOM){return;}
    if(index==_focus){var focusHeight=ROW_PITCH-4;dc.setColor(0x330000,Graphics.COLOR_TRANSPARENT);dc.fillRoundedRectangle(54,cy-focusHeight/2,346,focusHeight,8);dc.setColor(Graphics.COLOR_RED,Graphics.COLOR_TRANSPARENT);dc.setPenWidth(2);dc.drawRoundedRectangle(54,cy-focusHeight/2,346,focusHeight,8);if(_editing){dc.fillRectangle(61,cy-4,8,8);}else{dc.fillCircle(65,cy,3);}}
    var vjust=Graphics.TEXT_JUSTIFY_VCENTER;dc.setColor(Graphics.COLOR_LT_GRAY,Graphics.COLOR_TRANSPARENT);dc.drawText(76,cy,font,label,Graphics.TEXT_JUSTIFY_LEFT|vjust);if(value!=null){dc.setColor(Graphics.COLOR_WHITE,Graphics.COLOR_TRANSPARENT);dc.drawText(382,cy,font,value,Graphics.TEXT_JUSTIFY_RIGHT|vjust);}
  }
  function onUpdate(dc){dc.setColor(Graphics.COLOR_BLACK,Graphics.COLOR_BLACK);dc.clear();if(_screen==LOCATE){drawLocate(dc);}else if(_screen==GPS){drawGps(dc);}else if(isEditor()){drawEditor(dc);}else if(_screen==ATMOS){drawAtmos(dc);}else if(_screen==CALC){drawCalc(dc);}else if(_screen==DISPLAY){drawDisplay(dc);}else if(_screen==ACTIONS){drawActions(dc);}else if(_screen==DETAILS){drawDetails(dc);}else if(_screen==HELP){drawHelp(dc);}else if(_screen==GPS_WARNING){drawGpsWarning(dc);}else if(_screen==DISCARD){drawDiscard(dc);}else if(_screen==CALC_ERROR){drawError(dc);}}

  function drawLocate(dc){var first=_model.firstUse&&!_model.hasLocation();var titleTop=8;var titleHeight=dc.getFontHeight(Graphics.FONT_SMALL);var hintTop=titleTop+titleHeight+6;var hintHeight=dc.getFontHeight(Graphics.FONT_XTINY);var rowHeight=hintHeight+8;_rowTop=hintTop+hintHeight+6+(rowHeight/2);if(_rowTop<116){_rowTop=116;}row(dc,0,s(Rez.Strings.Latitude),coord(_model.latitude,true));row(dc,1,s(Rez.Strings.Longitude),coord(_model.longitude,false));row(dc,2,s(Rez.Strings.Elevation),_model.elevation==null?s(Rez.Strings.NoLocation):_model.elevation.format("%.0f")+" m");row(dc,3,s(Rez.Strings.Gps),"");row(dc,4,s(Rez.Strings.Format),_model.formatDms?s(Rez.Strings.Dms):s(Rez.Strings.Decimal));row(dc,5,s(Rez.Strings.Atmosphere),"");row(dc,6,_model.confirmed?s(Rez.Strings.Calculate):s(Rez.Strings.ConfirmLocation),"");row(dc,7,s(Rez.Strings.Help),"");title(dc,s(Rez.Strings.Locate));if(first){dc.setColor(Graphics.COLOR_LT_GRAY,Graphics.COLOR_TRANSPARENT);dc.drawText(227,hintTop,Graphics.FONT_XTINY,s(Rez.Strings.FirstUse),Graphics.TEXT_JUSTIFY_CENTER);}if(_model.hasLocation()){footer(dc,s(Rez.Strings.Source)+": "+sourceText());}}
  function sourceText(){if(_model.adjusted){return s(Rez.Strings.GpsAdjusted);}if(_model.source=="GPS"){return "GPS";}if(_model.source=="Manual"){return s(Rez.Strings.Manual);}return s(Rez.Strings.Saved);}
  function coord(value,isLat){if(value==null){return s(Rez.Strings.NoLocation);}var a=value.abs();var hemi=isLat?(value<0?"S":"N"):(value<0?"W":"E");if(!_model.formatDms){return a.format("%.5f")+"° "+hemi;}var d=a.toNumber();var mf=(a-d)*60.0;var m=mf.toNumber();var sec=Math.round((mf-m)*60.0).toNumber();if(sec==60){sec=0;m+=1;}if(m==60){m=0;d+=1;}return Lang.format("$1$°$2$′$3$″ $4$",[d,m,sec,hemi]);}

  function drawGps(dc){_rowTop=276;title(dc,s(Rez.Strings.GpsTitle));var elapsed=Time.now().value()-_gpsStarted;var state=_gpsError!=null?_gpsError:(_gpsLat==null?(elapsed>=60?s(Rez.Strings.NoFix):s(Rez.Strings.Searching)):_gpsQuality);center(dc,75,Graphics.FONT_SMALL,state,Graphics.COLOR_WHITE);center(dc,112,Graphics.FONT_XTINY,s(Rez.Strings.Elapsed)+": "+formatElapsed(elapsed),Graphics.COLOR_LT_GRAY);if(_gpsLat!=null){center(dc,148,Graphics.FONT_XTINY,coord(_gpsLat,true),Graphics.COLOR_LT_GRAY);center(dc,174,Graphics.FONT_XTINY,coord(_gpsLon,false),Graphics.COLOR_LT_GRAY);center(dc,200,Graphics.FONT_XTINY,_gpsElev.format("%.0f")+" m",Graphics.COLOR_LT_GRAY);if(_gpsQualityCode==Position.QUALITY_LAST_KNOWN&&_gpsWhen!=null){center(dc,224,Graphics.FONT_XTINY,s(Rez.Strings.Age)+": "+formatElapsed(Time.now().value()-_gpsWhen),Graphics.COLOR_DK_GRAY);}}row(dc,0,s(Rez.Strings.UseLocation),_gpsLat==null?"—":"");row(dc,1,s(Rez.Strings.EnterManual),"");row(dc,2,s(Rez.Strings.Cancel),"");centerFit(dc,414,"START",Graphics.COLOR_DK_GRAY,Graphics.FONT_XTINY,Graphics.FONT_XTINY,130);}
  function formatElapsed(n){return Lang.format("$1$:$2$",[(n/60).format("%02d"),(n%60).format("%02d")]);}

  function isEditor(){return _screen==EDIT_LAT||_screen==EDIT_LON||_screen==EDIT_ELEV;}
  function beginEditor(screen){_screen=screen;_focus=0;_scroll=0;_editing=false;_invalid=false;_editOriginal=screen==EDIT_LAT?_model.latitude:(screen==EDIT_LON?_model.longitude:_model.elevation);var v=_editOriginal==null?0.0:_editOriginal;_negative=v<0;_digits=[];var count=screen==EDIT_LAT?7:(screen==EDIT_LON?8:5);var scaled;if(screen==EDIT_ELEV){scaled=Math.round(v.abs()).toNumber();}else if(_model.formatDms){var a=v.abs();var d=a.toNumber();var mm=(a-d)*60.0;var m=mm.toNumber();var sec=Math.round((mm-m)*60.0).toNumber();scaled=d*10000+m*100+sec;count=(screen==EDIT_LAT?6:7);}else{scaled=Math.round(v.abs()*100000.0).toNumber();}for(var i=count-1;i>=0;i--){_digits.add((scaled/Math.pow(10,i)).toNumber()%10);}WatchUi.requestUpdate();}
  function digitLabel(i){if(i==0){return s(_screen==EDIT_ELEV?Rez.Strings.Sign:Rez.Strings.Hemisphere);}if(_screen==EDIT_ELEV){var p=4-(i-1);return p==0?"m":"m x "+Math.pow(10,p).format("%d");}var degreeDigits=_screen==EDIT_LAT?2:3;if(i<=degreeDigits){return "° x "+Math.pow(10,degreeDigits-i).format("%d");}if(_model.formatDms){var j=i-degreeDigits;return j<=2?(j==1?"′ x 10":"′ x 1"):(j==3?"″ x 10":"″ x 1");}var f=i-degreeDigits;return "° x 0."+repeatZero(f-1)+"1";}
  function repeatZero(n){var x="";for(var i=0;i<n;i++){x+="0";}return x;}
  function editorValue(i){if(i==0){if(_screen==EDIT_LAT){return _negative?"S":"N";}if(_screen==EDIT_LON){return _negative?"W":"E";}return _negative?"-":"+";}return _digits[i-1].toString();}
  function drawEditor(dc){_rowTop=82;title(dc,s(_screen==EDIT_LAT?Rez.Strings.EditLatitude:(_screen==EDIT_LON?Rez.Strings.EditLongitude:Rez.Strings.EditElevation)));for(var i=0;i<=_digits.size();i++){row(dc,i,digitLabel(i),editorValue(i));}row(dc,_digits.size()+1,s(Rez.Strings.Done),"");if(_invalid){center(dc,374,Graphics.FONT_XTINY,s(Rez.Strings.InvalidCoordinate),Graphics.COLOR_RED);}footer(dc,_editing?s(Rez.Strings.Changing):s(Rez.Strings.SelectDigit));}
  function changeDigit(delta){if(_focus==0){_negative=!_negative;return;}var idx=_focus-1;var max=9;if(_model.formatDms&&_screen!=EDIT_ELEV){var dd=_screen==EDIT_LAT?2:3;var part=idx+1-dd;if(part==1||part==3){max=5;}}var v=_digits[idx]+delta;if(v<0){v=max;}if(v>max){v=0;}_digits[idx]=v;_invalid=false;}
  function editorNumber(){var total=0;for(var i=0;i<_digits.size();i++){total=total*10+_digits[i];}var v;if(_screen==EDIT_ELEV){v=total;}else if(_model.formatDms){var d=(total/10000).toNumber();var m=((total%10000)/100).toNumber();var sec=total%100;v=d+m/60.0+sec/3600.0;}else{v=total/100000.0;}return _negative?-v:v;}
  function commitEditor(){var v=editorNumber();var av=v.abs();var max=_screen==EDIT_LAT?90.0:(_screen==EDIT_LON?180.0:99999.0);if(av>max){_invalid=true;_focus=1;_scroll=0;return;}if(_screen!=EDIT_ELEV&&_model.formatDms){var total=0;for(var i=0;i<_digits.size();i++){total=total*10+_digits[i];}var d=(total/10000).toNumber();var m=((total%10000)/100).toNumber();var sec=total%100;if(m>59){_invalid=true;_focus=_digits.size()-3;return;}if(sec>59){_invalid=true;_focus=_digits.size()-1;return;}if(d==max&&(m!=0||sec!=0)){_invalid=true;_focus=_digits.size()-3;return;}}else if(_screen!=EDIT_ELEV&&av==max){var whole=av.toNumber();if(av-whole>0){_invalid=true;_focus=(_screen==EDIT_LAT?3:4);return;}}
    if(_screen==EDIT_LAT){_model.latitude=v;}else if(_screen==EDIT_LON){_model.longitude=v;}else{_model.elevation=v;}_model.adjusted=_model.source=="GPS";if(!_model.adjusted){_model.source="Manual";}_model.confirmed=false;open(LOCATE);}

  function drawAtmos(dc){_rowTop=82;title(dc,s(Rez.Strings.Atmosphere));var mode=_model.pressureMode==0?s(Rez.Strings.Automatic):(_model.pressureMode==1?s(Rez.Strings.PressureManual):s(Rez.Strings.RefractionOff));row(dc,0,s(Rez.Strings.Pressure),mode);if(_model.pressureMode==1){row(dc,1,s(Rez.Strings.ObserverPressure),_model.manualPressure.format("%.1f")+" hPa");}row(dc,2,s(Rez.Strings.Temperature),_model.temperature.format("%.1f")+"°C");row(dc,3,s(Rez.Strings.Humidity),_model.humidity.format("%.0f")+"%");row(dc,4,s(Rez.Strings.Wavelength),"0.55 um");row(dc,5,s(Rez.Strings.Alert),_model.calculationAlert?s(Rez.Strings.On):s(Rez.Strings.Off));row(dc,6,s(Rez.Strings.Done),"");}

  function drawCalc(dc){title(dc,_restart?s(Rez.Strings.Restarting):s(Rez.Strings.Calculating));var labels=[Rez.Strings.ReadingPressure,Rez.Strings.LoadingEarth,Rez.Strings.ConvertingTime,Rez.Strings.CalculatingPolaris,Rez.Strings.ObserverCorrections,Rez.Strings.PreparingDisplay];center(dc,120,Graphics.FONT_SMALL,s(labels[_calcStage]),Graphics.COLOR_LT_GRAY);dc.setColor(0x330000,Graphics.COLOR_TRANSPARENT);dc.fillRectangle(52,190,350,20);dc.setColor(Graphics.COLOR_RED,Graphics.COLOR_TRANSPARENT);dc.fillRectangle(52,190,(350*_progress)/100,20);dc.drawRectangle(52,190,350,20);center(dc,230,Graphics.FONT_SMALL,_progress.format("%d")+"%",Graphics.COLOR_WHITE);footer(dc,s(Rez.Strings.CancelHint));}
  function drawError(dc){_rowTop=250;title(dc,s(Rez.Strings.CalculationError));drawWrapped(dc,_errorText,85);row(dc,0,s(Rez.Strings.TryAgain),"");row(dc,1,s(Rez.Strings.BackLocation),"");row(dc,2,s(Rez.Strings.Details),"");}
  function drawDisplay(dc){centerFit(dc,50,s(Rez.Strings.HourAngle),Graphics.COLOR_RED,Graphics.FONT_XTINY,Graphics.FONT_XTINY,200);if(_result==null){center(dc,170,Graphics.FONT_LARGE,"—",Graphics.COLOR_DK_GRAY);return;}var elapsed=Time.now().value()-_displayBase;var ha=_result[:hourAngle]+elapsed*1.0027379*Math.PI/43200.0;centerFit(dc,119,formatHa(ha),Graphics.COLOR_RED,Graphics.FONT_LARGE,Graphics.FONT_SMALL,340);center(dc,188,Graphics.FONT_XTINY,s(Rez.Strings.PoleDistance),Graphics.COLOR_LT_GRAY);centerFit(dc,245,formatPd(_result[:poleDistance]),Graphics.COLOR_RED,Graphics.FONT_SMALL,Graphics.FONT_XTINY,330);centerFit(dc,305,localDateTime(),Graphics.COLOR_LT_GRAY,Graphics.FONT_XTINY,Graphics.FONT_XTINY,380);if(_result[:warning]!=null){drawWrappedWidth(dc,s(_result[:warning]),354,410,280,50);return;}centerFit(dc,352,sourceText(),Graphics.COLOR_LT_GRAY,Graphics.FONT_XTINY,Graphics.FONT_XTINY,300);centerFit(dc,402,s(Rez.Strings.SelectAction),Graphics.COLOR_LT_GRAY,Graphics.FONT_XTINY,Graphics.FONT_XTINY,195);}
  function formatHa(rad){var v=rad-Math.floor(rad/Math.PI)*Math.PI;if(v<0){v+=Math.PI;}var n=Math.round(v*43200.0/Math.PI).toNumber()%43200;return Lang.format("$1$:$2$:$3$",[((n/3600).toNumber()).format("%02d"),(((n%3600)/60).toNumber()).format("%02d"),(n%60).format("%02d")]);}
  function formatPd(rad){var n=Math.round(rad*180.0/Math.PI*3600.0).toNumber();return Lang.format("$1$′ $2$″",[(n/60).toNumber(),n%60]);}
  function localDateTime(){var date=Gregorian.info(Time.now(),Time.FORMAT_SHORT);var c=System.getClockTime();var h=c.hour;var suffix="";if(!System.getDeviceSettings().is24Hour){suffix=" "+s(h<12?Rez.Strings.Am:Rez.Strings.Pm);h=h%12;if(h==0){h=12;}}return Lang.format("$1$-$2$-$3$  $4$:$5$:$6$$7$",[date.year,date.month,date.day,h.format("%02d"),c.min.format("%02d"),c.sec.format("%02d"),suffix]);}
  function drawActions(dc){_rowTop=104;title(dc,s(Rez.Strings.Actions));row(dc,0,s(Rez.Strings.Recalculate),"");row(dc,1,s(Rez.Strings.Location),"");row(dc,2,s(Rez.Strings.Atmosphere),"");row(dc,3,s(Rez.Strings.Details),"");}
  function detailsRows(){var r=[];r.add([s(Rez.Strings.Latitude),coord(_model.latitude,true)]);r.add([s(Rez.Strings.Longitude),coord(_model.longitude,false)]);r.add([s(Rez.Strings.Elevation),_model.elevation.format("%.0f")+" m MSL"]);r.add([s(Rez.Strings.Source),sourceText()]);r.add([s(Rez.Strings.Quality),_model.quality]);r.add([s(Rez.Strings.SavedAt),_model.savedAt==null?"—":_model.savedAt.toString()]);r.add([s(Rez.Strings.UtcTime),_resultTime==null?"—":_resultTime.toString()]);r.add([s(Rez.Strings.SeaPressure),_seaPressure==null?"—":_seaPressure.format("%.1f")+" hPa"]);r.add([s(Rez.Strings.ObserverPressure),_observerPressure.format("%.1f")+" hPa"]);r.add([s(Rez.Strings.DataSource),_pressureSource]);r.add([s(Rez.Strings.PressureSampleTime),_pressureTime==null?"—":_pressureTime.toString()]);r.add([s(Rez.Strings.Temperature),_model.temperature.format("%.1f")+"°C • "+s(Rez.Strings.DefaultSource)]);r.add([s(Rez.Strings.Humidity),_model.humidity.format("%.0f")+"% • "+s(Rez.Strings.DefaultSource)]);r.add([s(Rez.Strings.Wavelength),"0.55 um • Polaris"]);r.add([s(Rez.Strings.GeoidModel),s(Rez.Strings.GeoidProvenance)]);r.add([s(Rez.Strings.GeoidOffset),_geoidOffset==null?s(Rez.Strings.UnavailableData):_geoidOffset.format("%.6f")+" m"]);r.add([s(Rez.Strings.EllipsoidHeight),_ellipsoidHeight==null?s(Rez.Strings.UnavailableData):_ellipsoidHeight.format("%.6f")+" m"]);r.add([s(Rez.Strings.EarthSource),s(Rez.Strings.EarthDataProvenance)]);var mjd=_resultTime==null?null:40587.0+_resultTime/86400.0;r.add([s(Rez.Strings.SelectedMjd),mjd==null?"—":mjd.format("%.8f")]);r.add([s(Rez.Strings.EarthValidity),s(Rez.Strings.EarthValidityValue)]);r.add([s(Rez.Strings.EarthExpiry),s(Rez.Strings.EarthExpiryValue)]);r.add(["DUT1",_eop==null?"—":_eop[:dut1].format("%.9f")+" s"]);var arcsecFactor=180.0*3600.0/Math.PI;r.add(["xp / yp",_eop==null?"—":_eop[:xp].format("%.9f")+" / "+_eop[:yp].format("%.9f")+" rad"]);r.add(["xp / yp",_eop==null?"—":(_eop[:xp]*arcsecFactor).format("%.6f")+"″ / "+(_eop[:yp]*arcsecFactor).format("%.6f")+"″"]);r.add([s(Rez.Strings.CatalogSource),s(Rez.Strings.CatalogProvenance)]);r.add([s(Rez.Strings.CatalogEpoch),"J2000.0"]);r.add([s(Rez.Strings.ProperMotion),"RA +44.22 / Dec -11.74 mas/yr"]);r.add([s(Rez.Strings.Parallax),"7.54 mas"]);r.add([s(Rez.Strings.RadialVelocity),"-16.0 km/s"]);if(_result!=null){r.add([s(Rez.Strings.HourAnglePrecise),(_result[:hourAngle]*180.0/Math.PI).format("%.9f")+"°"]);r.add([s(Rez.Strings.PoleDistancePrecise),(_result[:poleDistance]*arcsecFactor).format("%.6f")+"″"]);}return r;}
  function drawDetails(dc){_rowTop=68;title(dc,s(Rez.Strings.Details));var r=detailsRows();for(var i=0;i<r.size();i++){row(dc,i,r[i][0],r[i][1]);}footer(dc,s(Rez.Strings.Back));}

  function drawHelp(dc){centerFit(dc,50,s(Rez.Strings.Help),Graphics.COLOR_RED,Graphics.FONT_XTINY,Graphics.FONT_XTINY,200);var pages=[Rez.Strings.HelpLocation,Rez.Strings.HelpFormats,Rez.Strings.HelpGps,Rez.Strings.HelpAtmosphere,Rez.Strings.HelpHour,Rez.Strings.HelpPole,Rez.Strings.HelpEarth];drawWrappedWidth(dc,s(pages[_helpPage]),110,360,300,50);centerFit(dc,410,s(Rez.Strings.Page)+" "+(_helpPage+1)+"/"+pages.size(),Graphics.COLOR_LT_GRAY,Graphics.FONT_XTINY,Graphics.FONT_XTINY,200);}
  function drawWrapped(dc,text,y){drawWrappedWidth(dc,text,y,190,300,50);}
  function drawWrappedWidth(dc,text,y,bottom,maxWidth,lineHeight){var font=Graphics.FONT_XTINY;var pos=0;while(pos<text.length()&&y<=bottom){var end=pos+1;var fit=end;var breakAt=-1;while(end<=text.length()){var part=text.substring(pos,end);if(dc.getTextWidthInPixels(part,font)>maxWidth){break;}fit=end;if(part.substring(part.length()-1,part.length())==" "){breakAt=end;}end+=1;}if(fit<=pos){fit=pos+1;}else if(end<=text.length()&&breakAt>pos){fit=breakAt;}var line=text.substring(pos,fit);center(dc,y,font,line,Graphics.COLOR_LT_GRAY);pos=fit;while(pos<text.length()&&text.substring(pos,pos+1)==" "){pos+=1;}y+=lineHeight;}}
  function drawGpsWarning(dc){_rowTop=244;title(dc,s(Rez.Strings.Acknowledge));center(dc,120,Graphics.FONT_SMALL,_gpsQuality,Graphics.COLOR_RED);row(dc,0,s(Rez.Strings.YesUse),"");row(dc,1,s(Rez.Strings.Cancel),"");}
  function drawDiscard(dc){_rowTop=244;title(dc,s(Rez.Strings.DiscardTitle));row(dc,0,s(Rez.Strings.Discard),"");row(dc,1,s(Rez.Strings.KeepEditing),"");}

  function maxFocus(){if(_screen==LOCATE){return 7;}if(_screen==GPS){return 2;}if(isEditor()){return _digits.size()+1;}if(_screen==ATMOS){return 6;}if(_screen==ACTIONS){return 3;}if(_screen==GPS_WARNING||_screen==DISCARD){return 1;}if(_screen==CALC_ERROR){return 2;}if(_screen==DETAILS){return detailsRows().size()-1;}return 0;}
  function navigate(delta){if(isEditor()&&_editing){changeDigit(delta);WatchUi.requestUpdate();return;}if(_screen==ATMOS&&_editing){changeAtmos(delta);WatchUi.requestUpdate();return;}if(_screen==HELP){_helpPage+=delta;if(_helpPage<0){_helpPage=6;}if(_helpPage>6){_helpPage=0;}WatchUi.requestUpdate();return;}var max=maxFocus();_focus+=delta;if(_focus<0){_focus=max;}if(_focus>max){_focus=0;}if(_screen==ATMOS){_focus=atmosphereVisibleFocus(_focus,delta,_model.pressureMode==1);}ensureFocusVisible();WatchUi.requestUpdate();}
  function select(){if(_screen==LOCATE){selectLocate();}else if(_screen==GPS){selectGps();}else if(isEditor()){if(_focus==_digits.size()+1){commitEditor();}else if(_editing){_editing=false;_focus+=1;ensureFocusVisible();}else{_editing=true;}}else if(_screen==ATMOS){selectAtmos();}else if(_screen==DISPLAY){open(ACTIONS);}else if(_screen==ACTIONS){if(_focus==0){beginCalculation(false);}else if(_focus==1){open(LOCATE);}else if(_focus==2){open(ATMOS);}else{open(DETAILS);}}else if(_screen==GPS_WARNING){if(_focus==0){acceptGps();}else{open(GPS);}}else if(_screen==DISCARD){if(_focus==0){_model.discardLocationChanges();WatchUi.popView(WatchUi.SLIDE_RIGHT);}else{open(LOCATE);}}else if(_screen==CALC_ERROR){if(_focus==0){beginCalculation(false);}else if(_focus==1){open(LOCATE);}else{open(DETAILS);}}WatchUi.requestUpdate();}
  function selectLocate(){if(_focus==0){beginEditor(EDIT_LAT);}else if(_focus==1){beginEditor(EDIT_LON);}else if(_focus==2){beginEditor(EDIT_ELEV);}else if(_focus==3){beginGps();}else if(_focus==4){_model.formatDms=!_model.formatDms;_model.savePreferences();}else if(_focus==5){open(ATMOS);}else if(_focus==6){if(!_model.hasLocation()){return;}if(!_model.confirmed){_model.confirm();}else{beginCalculation(false);}}else{open(HELP);}}
  function selectAtmos(){if(_focus==0){_model.pressureMode=(_model.pressureMode+1)%3;}else if((_focus==1&&_model.pressureMode==1)||_focus==2||_focus==3){_editing=!_editing;}else if(_focus==5){_model.calculationAlert=!_model.calculationAlert;}else if(_focus==6){_model.savePreferences();open(LOCATE);}}
  function changeAtmos(delta){if(_focus==1){_model.manualPressure+=delta*0.1;if(_model.manualPressure<300){_model.manualPressure=300;}if(_model.manualPressure>1100){_model.manualPressure=1100;}_model.manualPressureSet=true;}else if(_focus==2){_model.temperature+=delta;if(_model.temperature<(-80)){_model.temperature=-80;}if(_model.temperature>60){_model.temperature=60;}}else if(_focus==3){_model.humidity+=delta;if(_model.humidity<0){_model.humidity=0;}if(_model.humidity>100){_model.humidity=100;}}}
  function tap(y){if(_screen==DISPLAY||_screen==HELP){select();return;}var i=_scroll+((y-_rowTop+4)/ROW_PITCH).toNumber();if(i<0){i=0;}if(i>maxFocus()){i=maxFocus();}if(_screen==ATMOS&&i==1){var omittedCenter=_rowTop+(1-_scroll)*ROW_PITCH;i=atmosphereVisibleFocus(i,y<omittedCenter?-1:1,_model.pressureMode==1);}_focus=i;ensureFocusVisible();select();}
  function open(screen){_screen=screen;_focus=0;_scroll=0;_rowHalfHeight=0;_editing=false;WatchUi.requestUpdate();}
  function back(){if(isEditor()){open(LOCATE);}else if(_screen==LOCATE){if(_model.savedLatitude!=null&&_model.hasUnconfirmedChanges()){open(DISCARD);}else{WatchUi.popView(WatchUi.SLIDE_RIGHT);}}else if(_screen==GPS){getApp().stopGps();stopTimers();open(LOCATE);}else if(_screen==CALC){_cancelRequested=true;}else if(_screen==DISPLAY){open(LOCATE);}else if(_screen==ACTIONS){open(DISPLAY);}else if(_screen==DETAILS){open(_result==null?CALC_ERROR:ACTIONS);}else if(_screen==GPS_WARNING){open(GPS);}else if(_screen==DISCARD){open(LOCATE);}else if(_screen==CALC_ERROR||_screen==ATMOS||_screen==HELP){_model.savePreferences();open(LOCATE);}}

  function beginGps(){_gpsStarted=Time.now().value();_gpsLat=null;_gpsLon=null;_gpsElev=null;_gpsQuality="";_gpsWhen=null;_gpsError=null;open(GPS);try{getApp().startGps();}catch(e){_gpsError=s(Rez.Strings.Permission);}_timer.stop();_timer.start(method(:gpsTick),1000,true);}
  function gpsTick(){WatchUi.requestUpdate();}
  function onPosition(info){if(_screen!=GPS||info==null||info.position==null){return;}var d=info.position.toDegrees();_gpsLat=d[0];_gpsLon=d[1];_gpsElev=info.altitude==null?0.0:info.altitude;_gpsQualityCode=info.accuracy;_gpsQuality=qualityName(info.accuracy);_gpsWhen=info.when==null?null:info.when.value();_gpsReceived=Time.now().value();WatchUi.requestUpdate();}
  function qualityName(q){if(q==Position.QUALITY_GOOD){return s(Rez.Strings.GoodGps);}if(q==Position.QUALITY_USABLE){return s(Rez.Strings.UsableGps);}if(q==Position.QUALITY_POOR){return s(Rez.Strings.PoorGps);}if(q==Position.QUALITY_LAST_KNOWN){return s(Rez.Strings.LastKnown);}return s(Rez.Strings.Unavailable);}
  function selectGps(){if(_focus==0&&_gpsLat!=null){if(_gpsQualityCode==Position.QUALITY_POOR||_gpsQualityCode==Position.QUALITY_LAST_KNOWN){open(GPS_WARNING);}else{acceptGps();}}else if(_focus==1){getApp().stopGps();beginEditor(EDIT_LAT);}else if(_focus==2){getApp().stopGps();stopTimers();open(LOCATE);}}
  function acceptGps(){getApp().stopGps();stopTimers();_model.setLocation(_gpsLat,_gpsLon,_gpsElev,"GPS",_gpsQuality);_model.confirm();open(LOCATE);}

  function beginCalculation(restarting){if(!_model.confirmed||!_model.hasLocation()){showError(s(Rez.Strings.InvalidInputs));return;}if(_astroState!=null){Astrometry.cancel(_astroState);}_astroState=null;_restart=restarting;_screen=CALC;_calcStage=0;_progress=0;_pressureAttempts=0;_pressureSamples=[];_cancelRequested=false;_result=null;_errorText=null;_eop=null;stopTimers();_timer.start(method(:calculationChunk),50,false);WatchUi.requestUpdate();}
  function calculationChunk(){if(_cancelRequested){if(_astroState!=null){Astrometry.cancel(_astroState);_astroState=null;}_result=null;open(LOCATE);return;}try{if(_calcStage==0){if(samplePressure()){return;}_progress=25;_calcStage=1;}else if(_calcStage==1){loadEarthData();_progress=40;_calcStage=2;}else if(_calcStage==2){_resultTime=Time.now().value();beginAstronomy();_progress=50;_calcStage=3;}else if(_calcStage==3){if(!stepAstronomy()){_timer.start(method(:calculationChunk),50,false);WatchUi.requestUpdate();return;}_progress=90;_calcStage=4;}else if(_calcStage==4){checkVisibility();_progress=95;_calcStage=5;}else{finishCalculation();return;}_timer.start(method(:calculationChunk),50,false);WatchUi.requestUpdate();}catch(e){_astroState=null;showError(_errorText==null?s(Rez.Strings.AstronomyFailed):_errorText);}}
  function samplePressure(){if(_model.pressureMode!=0){finalizePressure();return false;}_pressureAttempts+=1;var info=Sensor.getInfo();if(info!=null&&info.pressure!=null){_pressureSamples.add(info.pressure/100.0);}_progress=(_pressureAttempts*25)/8;WatchUi.requestUpdate();if(_pressureAttempts<8){_timer.start(method(:calculationChunk),500,false);return true;}finalizePressure();return false;}
  function finalizePressure(){var now=Time.now().value();if(_model.pressureMode==2){_seaPressure=null;_observerPressure=0.0;_pressureSource=s(Rez.Strings.RefractionOff);return;}if(_model.pressureMode==1){_seaPressure=null;_observerPressure=_model.manualPressure;_pressureSource=s(Rez.Strings.Manual);return;}if(_pressureSamples.size()>0){var total=0.0;for(var i=0;i<_pressureSamples.size();i++){total+=_pressureSamples[i];}_seaPressure=total/_pressureSamples.size();_cachedSeaPressure=_seaPressure;_cachedPressureTime=now;_pressureSource=s(Rez.Strings.Barometer);_pressureTime=now;}else if(_cachedSeaPressure!=null&&now-_cachedPressureTime<=300){_seaPressure=_cachedSeaPressure;_pressureTime=_cachedPressureTime;_pressureSource=s(Rez.Strings.PressureRecent);}else if(_model.manualPressureSet){_seaPressure=null;_observerPressure=_model.manualPressure;_pressureSource=s(Rez.Strings.PressureFallback);return;}else{_seaPressure=1013.25;_pressureSource=s(Rez.Strings.StandardAtmosphere);_pressureTime=now;}var h=_model.elevation;var base=1.0-(0.0065*h)/(_model.temperature+273.15+0.0065*h);_observerPressure=_seaPressure*Math.pow(base,5.257);}
  function loadEarthData(){var now=Time.now().value();var mjd=40587.0+now/86400.0;_eop=EarthData.eop(mjd);if(_eop[:status]!=0){_errorText=s(Rez.Strings.EarthUnsupported);throw new Lang.Exception();}_geoidOffset=EarthData.geoidOffset(_model.latitude,_model.longitude);_ellipsoidHeight=EarthData.mslToEllipsoid(_model.latitude,_model.longitude,_model.elevation);}
  function beginAstronomy(){var jd=2440587.5+_resultTime/86400.0;var rc=(2.0+31.0/60.0+49.09/3600.0)*15.0*Math.PI/180.0;var dc=(89.0+15.0/60.0+50.8/3600.0)*Math.PI/180.0;_astroState=Astrometry.begin(rc,dc,44.22e-3*Math.PI/(180.0*3600.0),-11.74e-3*Math.PI/(180.0*3600.0),7.54e-3,-16.0,jd,0.0,_eop[:dut1],_model.longitude*Math.PI/180.0,_model.latitude*Math.PI/180.0,_ellipsoidHeight,_eop[:xp],_eop[:yp],_observerPressure,_model.temperature,_model.humidity/100.0,0.55);}
  function stepAstronomy(){var reply=Astrometry.step(_astroState);_astroState=reply[:state];_progress=50+(reply[:progress]*40).toNumber();if(!reply[:done]){return false;}var a=reply[:result];_astroState=null;if(a==null||a[:status]!=0){_errorText=s(Rez.Strings.AstronomyFailed);throw new Lang.Exception();}_result={:hourAngle=>a[:hob],:poleDistance=>(Math.PI/2.0-a[:dob]),:altitude=>(Math.PI/2.0-a[:zob]),:warning=>(_eop[:warning]?Rez.Strings.EarthExpires:null)};return true;}
  function checkVisibility(){if(_result[:altitude]<=0){_errorText=s(Rez.Strings.NotVisible);throw new Lang.Exception();}if(_result[:altitude]<5.0*Math.PI/180.0){_result[:warning]=Rez.Strings.WarningLow;}}
  function showError(text){stopTimers();_errorText=text;_screen=CALC_ERROR;_focus=0;_scroll=0;if(_model.calculationAlert){Attention.vibrate([new Attention.VibeProfile(40,1),new Attention.VibeProfile(40,0),new Attention.VibeProfile(40,1)]);}WatchUi.requestUpdate();}
  function finishCalculation(){_progress=100;_model.calculationSucceeded();_displayBase=_resultTime;_lastTick=Time.now().value();_lastAnchor=_lastTick;_restart=false;open(DISPLAY);_timer.start(method(:displayTick),1000,true);if(_model.calculationAlert){Attention.vibrate([new Attention.VibeProfile(50,1)]);}}
  function displayTick(){if(_screen!=DISPLAY){stopTimers();return;}var now=Time.now().value();var delta=now-_lastTick;if(delta<0||delta>3){beginCalculation(true);return;}_lastTick=now;if(now-_lastAnchor>=900){beginCalculation(false);return;}WatchUi.requestUpdate();}
}

class PolarFinderDelegate extends WatchUi.BehaviorDelegate {
  private var _view; function initialize(view){BehaviorDelegate.initialize();_view=view;}
  function onNextPage(){_view.navigate(1);return true;} function onPreviousPage(){_view.navigate(-1);return true;} function onSelect(){_view.select();return true;} function onBack(){_view.back();return true;}
  function onSwipe(evt){if(evt.getDirection()==WatchUi.SWIPE_UP){_view.navigate(1);}else if(evt.getDirection()==WatchUi.SWIPE_DOWN){_view.navigate(-1);}return true;}
  function onTap(evt){_view.tap(evt.getCoordinates()[1]);return true;}
}
